feature (angular-update): raise version to angular 10
plentymarkets/plugin-terra-basic pull request #79
Opened 2021-03-02 12:03 UTC by TimWieder

2021-03-03 09:23 UTC, MFrank84 requested changes

2021-03-03 09:23 UTC, MFrank84 commented on package.json
> +        "karma-jasmine-html-reporter": "^1.5.0",
Die Downgrades bitte Rückgängig machen

2021-03-03 09:23 UTC, MFrank84 commented on tslint.json
> +        "component-selector": [true, "element", ["ptb"], "kebab-case"],
Für TSLint sicherstellen, dass auch v1.0.1 von den terra-lint-rules isntalliert wird :)

2021-03-03 10:02 UTC, TimWieder commented on tslint.json
> +        "component-selector": [true, "element", ["ptb"], "kebab-case"],
Done

2021-03-03 10:09 UTC, MFrank84 requested changes

2021-03-03 10:09 UTC, MFrank84 commented on package.json
>          "karma-jasmine-html-reporter": "~1.5.4",
Alle Downgrades rückgängig machen 😃

2021-03-03 10:09 UTC, MFrank84 commented on tslint.json
> +        "component-selector": [true, "element", ["ptb"], "kebab-case"],
Laut package-lock wird noch 0.1.0 installiert

2021-03-04 13:51 UTC, pweyrich submitted a review, later dismissed

2021-03-05 08:08 UTC, MFrank84 approved these changes

2021-03-05 08:13 UTC, pweyrich approved these changes
tested 👍

2021-03-05 08:15 UTC, merged